# Generated by Django 4.2.4 on 2023-08-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_lojas', models.CharField(max_length=3)),
                ('Nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reflesh_Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_refresh', models.CharField(max_length=3)),
                ('Rf_tokens', models.CharField(max_length=100)),
                ('Hora_refresh', models.TimeField(auto_now_add=True)),
                ('Data_refresh', models.DateField(auto_now_add=True)),
                ('lojas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testeapp.lojas')),
            ],
        ),
        migrations.CreateModel(
            name='Access_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_access', models.CharField(max_length=3)),
                ('AC_token', models.CharField(max_length=100)),
                ('lojas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testeapp.lojas')),
            ],
        ),
    ]
